### ISSUE TITLE
Sequences aren't decoded correcly

### ISSUE THREAD

**Issue by mjhopkins** [smittytone/PreviewYaml#6]
**Test case to reproduce the issue**
This fails:

```yaml
name: My test YAML file
components:
- name: Component #1
  index: 0
- name: Component #2
  index: 1
```

while this succeeds:

```yaml
name: My test YAML file
components:
  - name: Component #1
    index: 0
  - name: Component #2
    index: 1
```

**Expectation:** both inputs should succeed, and give the same results.
